services:
  # backend:
  #   image: ${LOCAL_IMAGE_NAME}
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
  #     - RUN_ID=Test123
  #     - AWS_DEFAULT_REGION=eu-west-1
  #     - MODEL_LOCATION=/app/model
  #     - S3_ENDPOINT_URL=http://s3:4566/
  #   volumes:
  #     - "./model:/app/model"
  #s3:
  #  image: localstack/localstack
  #  ports:
  #    - "4566:4566"
  #  environment:
  #    - SERVICES=s3
  localstack_main:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - MAIN_CONTAINER_NAME=localstack_main
      - SERVICES=s3,sqs,ssm,sts
